[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mintedgem = "CdMkddBBv9zdB33UErvhzqH4XcZ3ZSxrBxY72Qo1vyUV"

[programs.devnet]
mintedgem = "CdMkddBBv9zdB33UErvhzqH4XcZ3ZSxrBxY72Qo1vyUV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/lainhathoang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
