[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mintedgem = "U7VaMo8JX3QrifomrL33dunx5tiqDmJZenU6vx4WneK"

[programs.devnet]
mintedgem = "U7VaMo8JX3QrifomrL33dunx5tiqDmJZenU6vx4WneK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/lainhathoang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
