[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mintedgem = "6nJtHYi1D6Vcxq5PXdusDWpB8M9GACHosMdch3yJgh6d"

[programs.devnet]
mintedgem = "6nJtHYi1D6Vcxq5PXdusDWpB8M9GACHosMdch3yJgh6d"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/Users/lainhathoang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
