[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mintedgem = "3Pc3EaRMQYkHd3Jxdf5Xk1vtwTzveaJrEs1KSVz6ZARb"

[programs.devnet]
mintedgem = "3Pc3EaRMQYkHd3Jxdf5Xk1vtwTzveaJrEs1KSVz6ZARb"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/Users/lainhathoang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
