[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mintedgem = "p4oawzVcmB9BSTKtDjRNhgbR4qFdHufnz5Zft2wNBF5"

[programs.devnet]
mintedgem = "p4oawzVcmB9BSTKtDjRNhgbR4qFdHufnz5Zft2wNBF5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/lainhathoang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
