[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mintedgem = "Dwtw4KSge4DxAnfiknpfvG6kFneFhsaYjkrqjEqvx1GR"

[programs.devnet]
mintedgem = "Dwtw4KSge4DxAnfiknpfvG6kFneFhsaYjkrqjEqvx1GR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/lainhathoang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
